name: Build macOS App

on: [push, pull_request]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: brew install sfml

      - name: Configure build
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Upload binary
        uses: actions/upload-artifact@v3
        with:
          name: my-sfml-app-macos
          path: build/my_app
