name: Build SFML App on macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SFML
        run: brew install sfml

      - name: Configure build
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build project
        run: cmake --build build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: custom_testing-macos
          path: build/bin/custom_testing

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SFML
        run: sudo apt-get update && sudo apt-get install -y libsfml-dev cmake g++

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build the project
        run: cmake --build build

      - name: Upload Executable
        uses: actions/upload-artifact@v3
        with:
          name: custom_testing-linux
          path: build/bin/custom_testing
