name: Build SFML App on macOS and Linux

on:
  push:
    branches: [ release ]
  pull_request:
    branches: [ release ]

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and install SFML from source (static)
        run: |
          git clone --branch 3.0.0 https://github.com/SFML/SFML.git
          mkdir SFML/build && cd SFML/build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DBUILD_SHARED_LIBS=OFF \
                   -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/SFML/install
          cmake --build . --config Release
          cmake --install .

      - name: Show full SFML install tree
        run: |
          echo "=== SFML Install Tree ==="
          find ${{ github.workspace }}/SFML/install
          echo "=========================="

      - name: Debug install output
        run: ls -R ${{ github.workspace }}/SFML/install/lib/cmake/SFML

      - name: Configure project build
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DSFML_DIR=${{ github.workspace }}/SFML/install/lib/cmake/SFML

      - name: Build project
        run: cmake --build build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: custom_testing-macos
          path: build/**

  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SFML dependencies (X11, OpenGL, Audio)
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            g++ \
            libx11-dev \
            libxrandr-dev \
            libxcursor-dev \
            libxi-dev \
            libgl1-mesa-dev \
            libudev-dev \
            libfreetype-dev \
            libflac-dev \
            libogg-dev \
            libvorbis-dev \
            libopenal-dev

      - name: Build and install SFML from source (static)
        run: |
          git clone --branch 3.0.0 https://github.com/SFML/SFML.git
          mkdir SFML/build && cd SFML/build
          cmake .. -DCMAKE_BUILD_TYPE=Release \
                   -DBUILD_SHARED_LIBS=OFF \
                   -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/SFML/install
          cmake --build . --config Release
          cmake --install .

      - name: Configure project build
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -DSFML_DIR=${{ github.workspace }}/SFML/install/lib/cmake/SFML

      - name: Build project
        run: cmake --build build

      - name: Upload Executable
        uses: actions/upload-artifact@v4
        with:
          name: custom_testing-linux
          path: build/**
